(**** beginning of start.txt ****)
(This file is for a MakerBot Thing-O-Matic)
(**** begin initilization commands ****)
G21 (set units to mm)
G90 (set positioning to absolute)
M108 S255 (set extruder speed to maximum)
M103 (Make sure extruder is off)
M104 S225 T0 (set extruder temperature)
M109 S125 T0 (set heated-build-platform temperature)
(**** end initilization commands ****)
(**** begin homing ****)
M138 (Go Home!)
(**** end homing ****)
(**** begin pre-wipe commands ****)
G1 X0 Y0 Z20 F3300.0 (move to waiting position)
M6 T0 (wait for toolhead parts, nozzle, HBP, etc., to reach temperature)
M101 (Extruder on, forward)
G04 P5000 (Wait t/1000 seconds)
M103 (Extruder off)
(**** end pre-wipe commands ****)
(**** end of start.txt ****)

